on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/volkertb/cicd-qemu-dos-docker:v1.7
      options: --device=/dev/kvm --cpus 1
    steps:
      - name: Test KVM
        run: |
          ls -lh /dev/kvm
          /usr/local/bin/run_cicd_dos.sh
